name: "Build Docker Image"
description: "Build Docker Image and Push Image to DockerHub"

inputs:
  context:
    description: "Which directory to set as docker build context"
    required: true
  tag:
    description: "Tag to push to dockerhub"
    required: true
    default: "latest"
  username:
    description: "DockerHub Username"
    required: true
  password:
    description: "DockerHub Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      run: docker login --username=${{ inputs.username }} --password=${{ inputs.password }}
      shell: bash

    - name: Build the Docker image
      run: docker build ${{ inputs.context }} --tag ${{ inputs.tag }} --build-arg NG_CONFIGURATION=production
      shell: bash

    - name: Push to DockerHub
      run: docker push ${{ inputs.tag }}
      shell: bash
