services:
  devcontainer:
    container_name: ${COMPOSE_PROJECT_NAME:-bosandev}-devcontainer
    build: "."
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: node
    volumes:
      - ..:/workspace:cached
    environment:
      DB_HOST: ${COMPOSE_PROJECT_NAME:-bosandev}-postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
      DB_SCHEMA: public
      DATABASE_URI: mongodb://${COMPOSE_PROJECT_NAME:-bosandev}-mongo/bosan
      CORS_ENABLE: "true"
      CORS_ORIGINS: "http://localhost:4200,http://localhost:4300"

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME:-bosandev}-postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer

  mongo:
    container_name: ${COMPOSE_PROJECT_NAME:-bosandev}-mongo
    image: mongo:4.2
    environment:
      MONGO_INITDB_DATABASE: bosan

  mongoexpress:
    container_name: ${COMPOSE_PROJECT_NAME:-bosandev}-mongoexpress
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: ${COMPOSE_PROJECT_NAME:-bosandev}-mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
