name: Build client-admin

on:
  push:
    branches:
      - master
    paths:
      - client-admin/**
      - ".github/workflows/master-build-client-admin.yml"
      - ".github/workflows/build-docker.yml"

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: ./.github/actions/build-docker
        with:
          context: "./client-admin"
          tag: "latest"
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
