name: Build client

on:
  push:
    branches:
      - master
    paths:
      - client/**
      - ".github/workflows/master-build-client.yml"
      - ".github/workflows/build-docker.yml"

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: ./.github/actions/build-docker
        with:
          context: "./client"
          tag: "bosancz/bosan.cz-client:latest"
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
