name: Build server (test)

on:
  pull_request:
    types: [review_requested]
    paths:
      - server/**
      - ".github/workflows/master-build-server.yml"
      - ".github/workflows/build-docker.yml"

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./.github/actions/build-docker
        with:
          context: "./server"
          tag: "test"
