name: Build server (test)

on:
  pull_request:
    types: [review_requested, synchronize]
    paths:
      - server/**
      - ".github/workflows/master-build-server.yml"
      - ".github/workflows/build-docker.yml"

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: ./.github/actions/build-docker
        with:
          context: "./server"
          tag: "test"
          username: "${{secrets.DOCKER_USERNAME}}"
          password: "${{secrets.DOCKER_PASSWORD}}"
