name: Build server (test)

on:
  push:
    branches:
      - test
    paths:
      - server/**
      - ".github/workflows/test-build-server.yml"

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build ./server --tag bosancz/bosan.cz-server:test
      - name: Login to DockerHub
        run: docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
      - name: Push to DockerHub
        run: docker push bosancz/bosan.cz-server:test
